# Name of your site 
name: Project Linework

# Short description (goes below the title; it will also be used in the RSS feed)
description: Handcrafted Vector Linework for Cartography

# Your name, as you want it to appear underneath each post and in the footer
author: Sam Matthews

baseurl: http://svmatthews.github.io/project-linework/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

pygments: false

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: false

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md]
